version: '3.1'
services:
  # MongoDB container
  mongohost:
    image: mongo:7
    container_name: mongoHost
    restart: always
    ports:
      - "27017:27017"  # Expose the default MongoDB port
    volumes:
      - mongohost_db:/data/db  # Persist MongoDB data on the host machine

  # .NET API container
  restapi:
    build: .  # Build from the Dockerfile in the current directory
    container_name: restapi
    restart: always
    ports:
      - "5001:5001"  # Expose port 8081 of the container as port 5000 on the host
    depends_on:
      - mongohost  # Ensure MongoDB container starts before the API

# Volumes section for MongoDB persistence
volumes:
  mongohost_db:
